[package]
name = "bevy-hex-example"
version = "0.1.0"
authors = ["Pi Lanningham <pi@attentivemobile.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
bevy = "0.4.0"